# Runs the application and full suite of services it depends on
version: '3.9'

services:

  redis:
    image: redis:7.2
    networks:
      - hmpps
    container_name: nona-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: nona-hmpps-auth
    ports:
      - '9090:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/auth/health']
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  app:
    build:
      context: .
      args:
        BUILD_NUMBER: 2023-05-18.1.39b1b24
        GIT_REF: unknown
        GIT_BRANCH: unknown
    networks:
      - hmpps
    depends_on:
      - redis
      - hmpps-auth
    ports:
      - '3000:3000'
    environment:
      - PRODUCT_ID=DPS032
      - INGRESS_URL=http://localhost:3000
      - REDIS_HOST=redis
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - TOKEN_VERIFICATION_API_URL=http://hmpps-auth:8080/auth
      - TOKEN_VERIFICATION_ENABLED=false
      # These will need to match new creds in the seed auth service auth
      - API_CLIENT_ID=client-id
      - API_CLIENT_SECRET=client-secret
      - SYSTEM_CLIENT_ID=system-client-id
      - SYSTEM_CLIENT_SECRET=system-client-secret
      - SESSION_SECRET=somesecretvalue

networks:
  hmpps:
