---
generic-service:
  replicaCount: 2

  ingress:
    host: non-associations-preprod.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: preprod

    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    OFFENDER_SEARCH_API_URL: "https://prisoner-offender-search-preprod.prison.service.justice.gov.uk"
    HMPPS_NON_ASSOCIATIONS_API_URL: "https://non-associations-api-preprod.hmpps.service.justice.gov.uk"

    INGRESS_URL: "https://non-associations-preprod.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support-preprod.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
