generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: non-associations-preprod.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: preprod

    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api-preprod.prison.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    OFFENDER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    HMPPS_NON_ASSOCIATIONS_API_URL: "https://non-associations-api-preprod.hmpps.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"

    INGRESS_URL: "https://non-associations-preprod.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support-preprod.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: hmpps-non-associations-preprod
  businessHoursOnly: true
