---
generic-service:
  replicaCount: 2

  ingress:
    host: non-associations-preprod.hmpps.service.justice.gov.uk
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=hmpps-non-associations"
      {{ if .Values.ingress.modsecurity_audit_enabled -}}
      SecAuditEngine RelevantOnly
      SecAuditLog /var/log/nginx/error.log
      SecAuditLogType Serial
      {{ end -}}
      SecRuleRemoveById 920300
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateTargetById 942100 "!ARGS"  # disable libinjection testing on request args. to disable all SQLi testing, modify rules in the range 942100-942999
      SecRuleUpdateTargetById 942430 "!ARGS:returnTo"
      SecAction \
        "id:900000,\
         phase:1,\
         nolog,\
         pass,\
         t:none,\
         setvar:tx.paranoia_level=2"

  env:
    ENVIRONMENT: preprod

    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    OFFENDER_SEARCH_API_URL: "https://prisoner-offender-search-preprod.prison.service.justice.gov.uk"
    HMPPS_NON_ASSOCIATIONS_API_URL: "https://non-associations-api-preprod.hmpps.service.justice.gov.uk"

    INGRESS_URL: "https://non-associations-preprod.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support-preprod.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
