---
generic-service:
  replicaCount: 2

  ingress:
    host: non-associations-dev.hmpps.service.justice.gov.uk

  allowlist: null

  env:
    ENVIRONMENT: dev

    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-dev.aks-dev-1.studio-hosting.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    OFFENDER_SEARCH_API_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    HMPPS_NON_ASSOCIATIONS_API_URL: "https://non-associations-api-dev.hmpps.service.justice.gov.uk"

    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"

    INGRESS_URL: "https://non-associations-dev.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-dev.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support-dev.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
