---
generic-service:
  nameOverride: hmpps-non-associations
  productId: DPS032

  # serviceAccountName: "hmpps-non-associations"

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-non-associations
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-non-associations-cert
    modsecurity_enabled: true  # enable OWASP core rules then handle false positives by removing or tweaking rules to not block specific args or cookies
    modsecurity_audit_enabled: false
    modsecurity_snippet: |
      SecRuleEngine On
      SecRuleRemoveById 920320
      SecRuleRemoveById 920300
      SecRuleRemoveById 920440
      SecRuleRemoveById 942110
      SecRuleRemoveById 913101
      SecRuleUpdateTargetById 931130 "!ARGS:/redirect_uri/"
      SecRuleUpdateTargetById 942440 "!REQUEST_COOKIES:/jwtSession/"
      SecRuleUpdateTargetById 942450 "!REQUEST_COOKIES:/jwtSession/"
      SecRuleUpdateTargetById 930120 "!REQUEST_COOKIES:/jwtSession/"
      SecRuleUpdateTargetById 942210 "!REQUEST_COOKIES:/jwtSession/"
      SecRuleUpdateTargetById 920450 "!REQUEST_HEADERS_NAMES:/accept-charset/"
      SecRuleUpdateTargetById 931130 "!ARGS:/registeredRedirectUriWithNewlines/"
      SecRuleUpdateTargetById 942430 "!ARGS:/registeredRedirectUriWithNewlines/"
      SecRuleUpdateTargetById 942440 "!REQUEST_COOKIES:/returnTo/"
      SecRuleUpdateTargetById 942450 "!REQUEST_COOKIES:/returnTo/"
      SecRuleUpdateTargetById 930120 "!REQUEST_COOKIES:/returnTo/"
      SecRuleUpdateTargetById 942210 "!REQUEST_COOKIES:/returnTo/"
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE"
      SecDefaultAction "phase:2,pass,log,tag:github_team=hmpps-non-associations"
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    BUNYAN_NO_COLOR: "1"
    AUDIT_ENABLED: "false"
    AUDIT_SQS_REGION: "eu-west-2"
    AUDIT_SERVICE_NAME: "UNASSIGNED"

  envFrom:
    - secretRef:
        name: hmpps-non-associations
    - secretRef:
        name: application-insights

  namespace_secrets:
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    # sqs-hmpps-audit-secret:
    #   AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
    #   AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform
      - prisons
      - private_prisons

  scheduledDowntime:
    timeZone: Europe/London

generic-prometheus-alerts:
  targetApplication: hmpps-non-associations
